document.addEventListener('DOMContentLoaded',function(){
if(!document.getElementById('minigame-content')||!document.getElementById('gameselect-menu')||!document.getElementById('back-to-menu')) return;
function clearContent(){
    if(!document.getElementById('minigame-content')||!document.getElementById('gameselect-menu')||!document.getElementById('back-to-menu')) return;
    document.getElementById('minigame-content').style.display='none';
    document.getElementById('minigame-content').innerHTML='';
    document.getElementById('gameselect-menu').style.display='flex';
    document.getElementById('back-to-menu').style.display='none';
}
function showGame(nm){
    if(!document.getElementById('minigame-content')||!document.getElementById('gameselect-menu')||!document.getElementById('back-to-menu')) return;
    document.getElementById('gameselect-menu').style.display='none';
    const mc=document.getElementById('minigame-content');mc.style.display='flex';mc.innerHTML='';document.getElementById('back-to-menu').style.display='inline-block';
    if(nm==='guess'){const box=document.createElement('div');box.className='minigame-box col-lg-6 mx-auto';box.innerHTML='<div class="minigame-title">حدس عدد</div><div class="minigame-desc">یک عدد تصادفی بین ۱ تا ۱۰۰ انتخاب شده، آیا می‌توانید آن را پیدا کنید؟</div><input type="number" id="guess-input" class="form-control mb-3" min="1" max="100" placeholder="عدد خود را وارد کنید" style="direction:rtl;"><button id="guess-btn" class="btn btn-primary w-100 mb-2">ثبت حدس</button><div id="guess-result" style="min-height:36px;"></div><button id="guess-restart" class="btn btn-outline-light w-100 mt-2" style="display:none;">شروع مجدد</button>';mc.appendChild(box);let answer=Math.floor(Math.random()*100)+1,tries=0;const input=document.getElementById('guess-input'),btn=document.getElementById('guess-btn'),result=document.getElementById('guess-result'),restart=document.getElementById('guess-restart');btn.onclick=function(){const val=+input.value;if(val<1||val>100||isNaN(val)){result.innerText='عدد وارد شده معتبر نیست.';return}tries++;if(val===answer){result.innerHTML='تبریک! درست حدس زدی. تعداد تلاش: '+tries;btn.style.display='none';restart.style.display='block'}else if(val<answer){result.innerHTML='عدد شما کوچک‌تر است!';}else{result.innerHTML='عدد شما بزرگ‌تر است!';}};input.onkeydown=function(e){if(e.key==='Enter'){btn.click()}};restart.onclick=function(){answer=Math.floor(Math.random()*100)+1;tries=0;input.value='';result.innerHTML='';btn.style.display='block';restart.style.display='none';input.focus()};}
if(nm==='ttt'){const tttBox=document.createElement('div');tttBox.className='minigame-box col-lg-6 mx-auto';tttBox.innerHTML='<div class="minigame-title">دوز (Tic-Tac-Toe)</div><div class="minigame-desc">با هوش مصنوعی ساده بازی کن! شما X هستید.</div><div id="ttt-board" style="display:grid;grid-template-columns:repeat(3,48px);gap:7px;justify-content:center;margin:0 auto 1.5rem auto;"></div><div id="ttt-result" style="min-height:40px;"></div><button id="ttt-restart" class="btn btn-outline-light w-100 mt-2">شروع مجدد</button>';mc.appendChild(tttBox);let board=["","","","","","","","",""],isUser=true,finished=false;function draw(){const b=document.getElementById('ttt-board');b.innerHTML='';board.forEach((cell,i)=>{const el=document.createElement('div');el.className='ttt-cell';el.style.cssText='width:48px;height:48px;font-size:2.1rem;display:flex;align-items:center;justify-content:center;background:rgba(6,182,212,0.08);border-radius:8px;cursor:'+(cell||finished?'default':'pointer')+';color:var(--primary-color);font-weight:800;transition:all 0.2s;box-shadow:0 1.5px 7px 1.5px rgba(0,0,0,0.07)';el.innerText=cell;if(!cell&&!finished)el.onclick=function(){if(isUser){board[i]='X';isUser=false;draw();setTimeout(aiMove,300)}};b.appendChild(el)});checkResult()}function aiMove(){if(finished)return;let idx=aiBestMove();if(idx!==-1){board[idx]='O';isUser=true;draw()}}function aiBestMove(){for(let i=0;i<9;i++)if(!board[i]){board[i]='O';if(checkWin('O')){board[i]='';return i}board[i]=''}for(let i=0;i<9;i++)if(!board[i]){board[i]='X';if(checkWin('X')){board[i]='';return i}board[i]=''}let moves=[];[0,2,6,8].forEach(i=>{if(!board[i])moves.push(i)});if(moves.length)return moves[Math.floor(Math.random()*moves.length)];if(!board[4])return 4;for(let i=0;i<9;i++)if(!board[i])moves.push(i);return moves.length?moves[Math.floor(Math.random()*moves.length)]:-1}function checkWin(p){const w=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];return w.some(comb=>comb.every(idx=>board[idx]===p))}function checkResult(){const res=document.getElementById('ttt-result');if(checkWin('X')){res.innerHTML='شما <b>برنده</b> شدید!';finished=true}else if(checkWin('O')){res.innerHTML='هوش مصنوعی <b>برنده</b> شد.';finished=true}else if(board.every(c=>c)){res.innerHTML='بازی <b>مساوی</b> شد.';finished=true}else{res.innerHTML='';finished=false}}document.getElementById('ttt-restart').onclick=function(){board=["","","","","","","","",""];isUser=true;finished=false;draw()};draw();}
if(nm==='memory'){const box=document.createElement('div');box.className='minigame-box col-lg-6 mx-auto';box.innerHTML='<div class="minigame-title">حافظه کارت</div><div class="minigame-desc">کارت‌های مشابه را با هم پیدا کن. همه کارت‌ها را باز کن!</div><div id="mem-board" style="display:grid;grid-template-columns:repeat(4,46px);gap:8px;justify-content:center;margin:0 auto 1.4rem auto;"></div><div id="mem-moves" style="min-height:32px;"></div><button id="mem-restart" class="btn btn-outline-light w-100 mt-2">شروع مجدد</button>';mc.appendChild(box);let icons=[1,2,3,4,5,6,7,8],deck=shuffle([...icons,...icons]),flipped=[],matched=[],moves=0,lock=false;function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function draw(){const b=document.getElementById('mem-board');b.innerHTML='';deck.forEach((v,i)=>{const d=document.createElement('div');d.className='mem-card';d.style.cssText='width:46px;height:46px;font-size:2rem;display:flex;align-items:center;justify-content:center;background:'+(flipped.includes(i)||matched.includes(i)?'var(--gradient-glow)':'rgba(6,182,212,0.10)')+';border-radius:7px;cursor:'+(matched.includes(i)?'default':'pointer')+';transition:all 0.2s;color:'+(flipped.includes(i)||matched.includes(i)?'var(--dark-color)':'var(--secondary-color)')+';box-shadow:0 2px 8px 1px rgba(0,0,0,0.05);font-weight:800;';if(flipped.includes(i)||matched.includes(i)){d.innerText=v}else{d.innerText='?'}if(!matched.includes(i)&&!flipped.includes(i))d.onclick=function(){if(lock)return;flipped.push(i);draw();if(flipped.length===2){lock=true;moves++;setTimeout(()=>{if(deck[flipped[0]]===deck[flipped[1]]){matched.push(flipped[0],flipped[1])}flipped=[];lock=false;draw()},800)}};b.appendChild(d)});const txt=document.getElementById('mem-moves');if(matched.length===deck.length&&deck.length>0){txt.innerHTML='کارت‌ها تموم شد! تلاش: '+moves}else{txt.innerHTML='تعداد حرکت: '+moves}}document.getElementById('mem-restart').onclick=function(){deck=shuffle([...icons,...icons]);flipped=[];matched=[];moves=0;lock=false;draw()};draw();}
if(nm==='reaction'){const box=document.createElement('div');box.className='minigame-box col-lg-6 mx-auto';box.innerHTML='<div class="minigame-title">تست واکنش سریع</div><div class="minigame-desc">سرعت واکنش خودت رو بسنج!</div><div id="rt-box" style="width:150px;height:54px;background:rgba(6,182,212,0.07);border-radius:12px;line-height:54px;margin:0 auto 1.7rem auto;font-size:1.13rem;transition:background .2s;text-align:center;cursor:pointer;color:var(--primary-color);font-weight:700;user-select:none;">برای شروع کلیک کن</div><div id="rt-result" style="min-height:33px;margin-bottom:8px"></div>';mc.appendChild(box);const boxEl=document.getElementById('rt-box'),result=document.getElementById('rt-result');let started=false,canClick=false,startTime,timeout;function reset(){started=false;canClick=false;result.innerText='';boxEl.style.background='rgba(6,182,212,0.07)';boxEl.innerText='برای شروع کلیک کن'}boxEl.onclick=function(){if(!started){reset();boxEl.innerText='منتظر شو...';started=true;timeout=setTimeout(()=>{canClick=true;startTime=Date.now();boxEl.style.background='var(--secondary-color)';boxEl.innerText='کلیک کن!'},Math.random()*1100+1100)}else if(started&&!canClick){clearTimeout(timeout);reset();result.innerText='خیلی زود کلیک کردی!'}else if(canClick){const time=Date.now()-startTime;boxEl.innerText='برای شروع کلیک کن';result.innerHTML='واکنش تو: <b>'+time+'</b> میلی‌ثانیه';started=false;canClick=false;boxEl.style.background='rgba(6,182,212,0.07)'}};}
if(nm==='color'){const box=document.createElement('div');box.className='minigame-box col-lg-6 mx-auto';box.innerHTML='<div class="minigame-title">انتخاب رنگ سریع</div><div class="minigame-desc">سریع‌ترین رنگ مورد نظر را پیدا کن و کلیک کن!</div><div id="cc-bar" style="min-height:32px;margin-bottom:10px;"></div><div id="cc-colors" style="display:flex;gap:9px;justify-content:center;flex-wrap:wrap;margin-bottom:10px;"></div><button id="cc-restart" class="btn btn-outline-light w-100 mt-2">شروع/دور بعد</button>';mc.appendChild(box);let colors=["#06b6d4","#f43f5e","#8b5cf6","#efd81d","#4ade80","#eab308","#f59e42","#6366f1"],target,t0,count=0,sum=0,playing=false;function newRound(){const cc=document.getElementById('cc-colors'),bar=document.getElementById('cc-bar');let shuffled=[...colors].sort(()=>.5-Math.random()),pick=Math.floor(Math.random()*shuffled.length);target=shuffled[pick];cc.innerHTML='';shuffled.forEach((c,i)=>{let d=document.createElement('div');d.style.cssText='width:40px;height:40px;background:'+c+';border-radius:10px;cursor:pointer;box-shadow:0 1.5px 6px 1.5px rgba(0,0,0,0.10);border:2.5px solid '+(c==target?'var(--accent-color)':'transparent')+';transition:all .18s;';d.onclick=function(){if(playing){let t=Date.now()-t0;bar.innerHTML='زمان شما: <b>'+t+'</b> میلی‌ثانیه';count++;sum+=t;playing=false}else{bar.innerHTML='برای شروع/دور بعد، دوباره بزن.'}};cc.appendChild(d)});bar.innerHTML='<span style="color:'+target+';font-weight:800;">روی رنگ '+target+' کلیک کن!</span>';t0=Date.now();playing=true}document.getElementById('cc-restart').onclick=function(){if(count){document.getElementById('cc-bar').innerHTML='میانگین: <b>'+(sum/count|0)+'</b> میلی‌ثانیه در '+count+' دور';count=0;sum=0}newRound()};newRound();}}}
if(document.querySelectorAll('.select-minigame').length)
    document.querySelectorAll('.select-minigame').forEach(btn=>{btn.onclick=function(){showGame(this.getAttribute('data-game'))}});
if(document.getElementById('back-to-menu'))
    document.getElementById('back-to-menu').onclick=clearContent;
clearContent();
});
